name: "Test"
on:
  push:
    branches:
      - "master"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Make sure you put workflow kit action on top of all the steps 
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: ${{ secrets.FORESIGHT_APIKEY }}
      - name: avs
        run: uname -a 
