name: "Test"
on:
  push:
    branches:
      - "master"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # Make sure you put workflow kit action on top of all the steps 
      - name: Collect Workflow Telemetry
        uses: runforesight/foresight-workflow-kit-action@v1
        if: ${{ always() }}
        with:
          api_key: 6d2cd3f0-d8bf-49eb-84e9-85681291d0e1
      - name: avs
        run: name -a 
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install GuardDog
        run: pip install guarddog

      - run: guarddog npm scan express --output-format sarif --exclude-rules repository_integrity_mismatch > guarddog.sarif

      - name: Upload SARIF file to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          category: guarddog-builtin
          sarif_file: guarddog.sari
